baseurl = "https://blog.fukajun.com"
title = "fukajun's blog"
languageCode = "ja-jp"
defaultContentLanguage = "ja"
hasCJKLanguage = true
summaryLength = 140
pluralizeListTitles = false
contentDir = "content"
googleAnalytics = "G-VBCRGHWQ32"
publishDir = "docs"

# Pagination
paginate = 5
paginatePath = "page"

# Theme to use
theme = "hugo-bootstrap-5"

[taxonomies]
  tag = "tags"
  category = "categories"

[languages.ja]
  languageName = "Japanese"

  # Replace the default footer message with a localized message
  copyright = ""

  #[[languages.ja.menu.main]]
  #  url = "/posts"
  #  name = "Home"
  #  weight = 1
  #[[languages.ja.menu.main]]
  #  url = "/about/"
  #  name = "About"
  #  weight = 2
  #[[languages.ja.menu.main]]
  #  url = "/contact/"
  #  name = "Contact"
  #  weight = 3

# Links format

[permalinks]
  post = "/:year/:month/:title/"

[params]
  # Main sections (currently used for the recent posts in the sidebar)
  mainSections = ["posts"]

  # Default author
  author = ""

  # Date format (default: Jan 2, 2006)
  date_format = "2006-01-02"

  # Display post summaries instead of content in list templates (default: true)
  truncate = true

  [params.sidebar]
    # Whether to show the recent posts or not (default: true)
    showRecent = true

    # Whether to show the taxonomies or not (default: true)
    # showTaxonomy = false

    # How many posts to show on the sidebar (Default: 5)
    # num_recent_posts = 10

  [params.header]
    # Color scheme for the header (default: "light")
    colorScheme = "light"

  [params.footer]
    # Color scheme for the footer (default: "light")
    # colorScheme = "dark"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "solarized-dark"
    tabWidth = 4
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
